version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    tty: true
    cap_add:
      - SYS_NICE
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mymoneydb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3307
    ports:
      - "3307:3307"

  backend:
    depends_on:
      - db
    entrypoint: /entrypoint.sh
    build: ./my-money-backend
    container_name: mymoney-backend-container
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./my-money-backend:/app/

  frontend:
    build: ./my-money-frontend
    depends_on:
      - backend
    container_name: mymoney-frontend-container
    ports:
      - 3000:3000
    volumes:
      - ./my-money-frontend:/app/
    stdin_open: true
    tty: true
